radanalyticsio/openshift-spark

Makefile
This makes it easier to set the local image name so that
builds associated with different projects in the same local
docker instance can be distinguished, for example
myproject/openshift-spark vs yourproject/openshift-spark
=> Add a LOCAL_IMAGE var to makefile

openshift-spark-py27-sti/Makefile, openshift-spark-py27-sti/README.md, python27_sti_base/Makefile
The point of this Makefile is to make it easy to generate
an openshift-spark image with a python s2i builder image as
as base, without having to manually maintain a duplicate
docker file. This alternate image has full support for
building pyspark applications which can be passed to
spark-submit, or python applications that invoke
spark-submit, or ...
=> Add a Makefile for generating an openshift-spark based on py s2i

scripts/spark/added/log4j.properties, scripts/spark/added/spark-defaults.conf, scripts/spark/install
The upcoming Spark 2.1 release will have some new properties of interest which may need to be adjusted at image build. This change provides reasonable defaults for the reverse proxy properties.
=> Add live conf files for log4j and spark default properties

Dockerfile
If the base image is changed to something that does not
end with the user set as root, then the initial layers will
fail.  Setting "USER root" early defends against that.
=> Move "USER root" to earlier in the Dockerfile

Dockerfile
Numpy is used by things like mllib so it should be
added to the standard image to be available to workers
=> Add numpy to the standard spark image

scripts/spark/added/launch.sh
Rather than have the pod creator set the SPARK_CONF_DIR environment
variable to point to a directory with a modified spark configuration, this change
simply copies the contents of $UPDATE_SPARK_CONF_DIR to $SPARK_HOME/conf
during startup. This gives us a simple overwrite semantic so that only files being
changed must be specified.
=> Copy local spark configuration to $SPARK_HOME/conf

.travis.yml, Dockerfile
Using customer build args we can do custom builds 
```bash
docker build -t openshift-spark --build-arg DISTRO_LOC=https://dist.apache.org/repos/dist/release/spark/spark-2.1.0/spark-2.1.0-bin-hadoop2.7.tgz --build-arg DISTRO_NAME=spark-2.1.0-bin-hadoop2.7
```
=> Removing hardcoded urls for custom build from CI

Dockerfile, scripts/spark/added/entrypoint, scripts/spark/added/launch.sh, scripts/spark/install
user still needs to run /entrypoint, but that's simpler than
cut&pasting nss setup commands
=> make it easier for users who shell into a container

scripts/spark/added/launch.sh
If the spark-defaults.conf file does not already contain
reverse proxy settings, add them before the spark service
is started.
=> Add reverse proxy settings if not explicitly set

scripts/spark/added/spark-defaults.conf
Tabs will mess up formatting for some things,
notably storage of text in configmaps
=> Remove extraneous tabs from config file

scripts/spark/added/launch.sh, scripts/spark/added/spark-defaults.conf
Due to the issue noted in jira SPARK-20853, this PR
removes the logic that enables reverse proxy by default
in the openshift-spark image.
=> Do not configure cluster for reverse proxy by default.

Dockerfile, README.md
This PR reduces the size of the image from 927 MB to ~~626~~ 683 MB.
Because other our images are based on this one, it'll also reduce their size.
update:
I've checked the modified image with the `https://radanalytics.io/resources.yaml` template and it works well.
update2:
..and the var notebook also worked well
@tmckayus could you please take a look?
=> Thinner docker image

scripts/spark/added/entrypoint
The launch.sh script does a small amount of work and
then execs the spark process with no long waits. Therefore,
as long as tini forwards signals, either bash or spark
should receive a SIGTERM and shut down quickly.
=> Run tini as pid 1 so that catches and forwards signals

modules/spark/install, openshift-spark-build/modules/spark/install
Some config files in the final image were dropped
in the move to concreate
=> Restore config files to /opt/spark/conf

image.yaml, modules/spark/check_for_download, modules/spark/install, openshift-spark-build/Dockerfile, openshift-spark-build/modules/spark/check_for_download, openshift-spark-build/modules/spark/install
* Pull spark from archives endpoint instead of release endpoint
This prevents us from losing a link if we lag behind apache releases.
* Use wildcards in spark install.
This is in prep for a release script to update spark version.
If we use wildcards, it's one less place we have to update.
=> Change spark release references

test/cmd/config-changes.sh, test/cmd/deploy.sh, test/cmd/deploy_jolokia.sh, test/cmd/deploy_prometheus.sh, test/common.sh, test/run.sh
This changes adds settings so that a locally build spark
image can be pushed to an integrated or external registry,
or an existing image can be used from an external registry.
=> Add env vars to allow testing non-local spark image

Makefile, change-yaml.sh, make-build-dir.sh, tag.sh
This change provides the following two scripts. When updating
some aspect of an image.yaml, both will be used. When only
modifying some image content under modules/, only the second
will be used.
* change-yaml.sh
This is for easily altering dependencies in the image.yaml file.
It modifies the well-known url based on the dependency version speicified
and calculates a new md5sum for each artifact.
* make-build-dir.sh
This is for regenerating the build dir based on the current
image.yaml file and repo content. It adds any resulting
changes to the commit
=> Add utility scripts to simplify changes

modules/spark/added/metrics.properties, openshift-spark-build/modules/spark/added/metrics.properties
Add  "application.source.jvm.class=org.apache.spark.metrics.source.JvmSource"
to metrics.properties sources
causing collection of detailed per job metrics
=> add application source to metrics.properties

modules/common/added/scripts/entrypoint, openshift-spark-build-inc-py36/Dockerfile, openshift-spark-build-inc-py36/help.md, openshift-spark-build-inc-py36/modules/common/added/scripts/entrypoint, openshift-spark-build-inc/Dockerfile, openshift-spark-build-inc/help.md, openshift-spark-build-inc/modules/common/added/scripts/entrypoint, openshift-spark-build-py36/Dockerfile, openshift-spark-build-py36/help.md, openshift-spark-build-py36/modules/common/added/scripts/entrypoint, openshift-spark-build/Dockerfile, openshift-spark-build/help.md, openshift-spark-build/modules/common/added/scripts/entrypoint
Quotes around $CMD in the invocations at the end of the script cause multi-word commands to be interpreted by bash as an atomic unit, and result in "No file found" type errors. Dropping the quotes lets the commands work correctly in these cases.
=> Remove quotes around command in entrypoint

.travis.release.images.sh, .travis.yml
This PR adds a script that for each image that we publish does `docker-squash` for the last 22 layers (23rd is the Centos base image layer) and pushes the image. For each commit to master it runs the same logic to create `:latest` images, for tags that matches the "regexp" x.y.z-n, it creates those image tags and also generates the `x.y.z-latest` so for instance if the git tag is `2.4.0-1`, it will create and push images for `:latest`, `2.4.0-1` and also `2.4-latest`.
profit if this is merged: images will be 300 megs smaller
todo:
/cc @elmiko
=> squash the docker images before pushing them manually to docker.io and quay.io

.travis.release.images.sh, .travis.yml
Fixing the typo in the `.travis.release.images.sh`
dbd5a759e:
```
[[ c1 -a c2 ]] --> [[ c1 -&& c2 ]]
```
d7e9cf9bf:
With the previous `.travis.yml` file, the deploy stage was run for each permutation of the matrix. This commit rewrites it from the matrix definition into explicit build stages.
b3ee5c98d:
Since the deploy and test stage do not share the same instance on AWS, the previously built docker images are not visible during the deploy stage and they need to be built again (or shared using travis cache, but this brings another set of problems). Building it again is relatively fast.
This is how the build looks like in travis:
https://travis-ci.org/radanalyticsio/openshift-spark/builds/535857574
=> typo in the .travis.release.images.sh

.travis.before.install.sh, .travis.release.images.sh, .travis.yml
* 1 commit is about smarter squashing, where the number of layers to squash is calculated based on the `docker history` command output (instead of hard-coded 22 value as it was)
* and the second commit is more a refactoring where I moved those lines from https://github.com/radanalyticsio/openshift-spark/blob/e8f3c489421a1b36fcee0d0af694a43d8baaa134/.travis.yml#L12:L16 to its own bash script and not running it in the deploy job when it wasn't necessary ... there is no need to install openshift if we wouldn't be pushing the images
=> Travis: calculate the number of layers for images to squash

README.md, image-inc.yaml, modules/s2i/added/assemble, modules/s2i/added/usage, openshift-spark-build-inc-py36/Dockerfile, openshift-spark-build-inc-py36/help.md, openshift-spark-build-inc-py36/modules/s2i/added/assemble, openshift-spark-build-inc-py36/modules/s2i/added/usage, openshift-spark-build-inc/Dockerfile, openshift-spark-build-inc/help.md, openshift-spark-build-inc/modules/s2i/added/assemble, openshift-spark-build-inc/modules/s2i/added/usage, openshift-spark-build-py36/Dockerfile, openshift-spark-build-py36/help.md, openshift-spark-build-py36/modules/s2i/added/assemble, openshift-spark-build-py36/modules/s2i/added/usage, openshift-spark-build/Dockerfile, openshift-spark-build/help.md, openshift-spark-build/modules/s2i/added/assemble, openshift-spark-build/modules/s2i/added/usage
This change supports an optional modify-spark directory that
can be put in the build input directory for image completion.
If the modify-spark directory is there, the image completion
script will run rsync to copy it's contents into the spark
install directory. This mechanism allows a user to modify
a spark distro by laying out a parallel directory structure.
=> Allow a modify-spark directory for image completion

make-build-dir.sh, modules/s2i/added/assemble, openshift-spark-build-inc/modules/s2i/added/assemble, openshift-spark-build-py36-inc/modules/s2i/added/assemble, openshift-spark-build-py36/modules/s2i/added/assemble, openshift-spark-build/modules/s2i/added/assemble
The rsync command used to enable the "modify-spark" behavior
in incomplete images was preserving permissions. However, it
was preserving permissions on files as uploaded by s2i, which
can't be relied on (it's not necessarily the same as perms on
disk from build_input). Therefore, preserving permissiosn has been
dropped, and a chmod to add group rwX to the spark installation
was moved until after the rsync.
=> Change modify-spark behavior for incomplete images and move chmod

modules/common/added/scripts/entrypoint, openshift-spark-build-inc/modules/common/added/scripts/entrypoint, openshift-spark-build-py36-inc/modules/common/added/scripts/entrypoint, openshift-spark-build-py36/modules/common/added/scripts/entrypoint, openshift-spark-build/modules/common/added/scripts/entrypoint
This is necessary to cause py36 to be the active version
for spark-on-k8s invocations of the openshift-spark images
that support py36.
=> Add SCL_ENABLE_CMD to spark-on-k8s entrypoint commands

.travis.release.images.sh
We tag images with x.y.z, and have a movable x.y-latest tag
that references the most recent x.y.z. Change the convention
and drop the -latest, just creating a movable x.y.
This will help deprecate some existing tools that rely on
x.y-latest, so that those versions will be effectively frozen.
=> Change the tagging of x.y-latest to just x.y

modules/common/added/scripts/launch.sh, openshift-spark-build-inc/modules/common/added/scripts/launch.sh, openshift-spark-build/modules/common/added/scripts/launch.sh
Checking if Spark master is up and running by trying port 7077
instead of depending on master's web ui service
=> Using 7077 port to check if master is listening
